name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - uses: Platane/snk@v2
        with:
          github_user_name: krishna-9016
          svg_out_path: dist/github-contribution-grid-snake.svg
          
      - name: Push to new branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -B output
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Generate snake animation"
          git push -f origin output
